language: node_js

node_js:
  - "node"

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  yarn: true
  directories:
    - node_modules

script:
  - yarn --version
  - yarn install
  - yarn setup
  - yarn lint
  - yarn test:nsp-warn
  - yarn test
#  - yarn test:routes
#  - yarn test:a11y
#  - yarn test:coverage
after_success:
#  - yarn test:codacy-upload
#  - yarn test:codecov-upload
